### ISSUE TITLE
AzureDevOps Build - YAML AWS Connection bug ?

### ISSUE THREAD

**Issue by steven-cuthill-otm** [aws/aws-vsts-tools#109]
Hello, 

Believe I have found a bug in the way the YAML build works over the Visual Designer when setting the awsCredentials property to the displayName of the AWS Service Connection i get the following error during build. you can see my YAML build sample below. I suspect that it's expecting the UUID for the connection rather than the name. I have given the connection liberal access rights so i don't think its down to ACL

Job Job1: Step  input awsCredentials references service connection Stevens TEMP which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.

```
pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
  displayName: 'CloudFormation Valadation Test'
  inputs:
    awsCredentials: 'Stevens TEMP'

    regionName: 'eu-west-1'

    filePath: 'build/cf-testScript.ps1'
```
