### ISSUE TITLE
It is not possible to use a variable or parameter in awsCredentials

### ISSUE THREAD

**Issue by xinin** [aws/aws-vsts-tools#303]
**Describe the bug**

When using a task of AWS VSTS it is necessary to indicate the connection of AWS against which you are going to execute the actions, inside our organization we want to make templates several solutions to facilitate the task to the development teams, reason why we need to pass as variable the value of awsCredentials.

The problem is that instead of evaluating the value of the variable it takes the literal to look for a valid connection.
**To reproduce**

```
parameters:
  env: ''

jobs:
- job: Build
  steps:
  - task: AWSShellScript@1
    inputs:
      awsCredentials: ${{ parameters.env }} 
      regionName: 'eu-west-1'
      scriptType: 'inline'
      inlineScript: |`
```

**Expected behavior**

The result of the execution is as follows:
```
The pipeline is not valid. Job Build: Step AWSShellScript input awsCredentials references service connection ${{ parameters.env }}  which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```
I tried to use a method similar to this to see if the problem was solved and the result is the same.

https://www.aaron-powell.com/posts/2019-05-24-azure-pipeline-templates-and-parameters/

**Your Environment**
 - VSTS or Azure Devops (on-prem or cloud based?): cloud based

**Comment by hunterwerlla** [comment]
As a workaround, you should be able to set `AWS.AccessKeyID` and `AWS.SecretAccessKey` variables in VSTS. Also if the system has AWS_ACCESS_KEY etc environment variables set it will also work.

**Comment by Slooz** [comment]
I'm able to accomplish exactly what you're attempting to do. Can you tell us how you're passing the `env` parameter into this template?

For example, I use this and it works for me:

    parameters:
      environment:
      environmentInAzurePipelines:
      serviceConnectionToAws:
      awsRegion:
    jobs:
      - deployment:
        environment: ${{ parameters.environmentInAzurePipelines }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
                  inputs:
                    awsCredentials: ${{ parameters.serviceConnectionToAws }}
                    regionName: ${{ parameters.awsRegion }}
                    scriptType: inline
                    inlineScript:

**Comment by xinin** [comment]
Finally we have achieved it, I do not know that we were doing badly in the sending of variables, possibly we would not be putting double bracket and we used parentesis or similar.

Thank you very much for your help.

```
#azure-pipeline.yml

jobs:
  - job:
    steps:
   - template: templates/create-infra.yml
      parameters: 
         env: $(ENV)

```
```
#create-infra.yml

parameters:
  env: ''

jobs:
- job: Build
  steps:
  - task: AWSShellScript@1
    inputs:
      awsCredentials: ${{ parameters.env }} 
      regionName: 'eu-west-1'
      scriptType: 'inline'

```
